services:
  caddy:
    image: caddy:2.9.1
    restart: unless-stopped
    networks:
      - caddy-net
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ${PWD}/data/hosted-files:/static/hosted-files:ro
      - ${PWD}/data/count-down-for-chornushka:/static/count-down-for-chornushka:ro
      - ${PWD}/data/h4folks:/static/h4folks:ro
      - ${PWD}/configs/caddy:/etc/caddy:ro
      - ${PWD}/data/caddy/data:/data
      - ${PWD}/data/caddy/config:/config

networks:
  caddy-net:
    driver: bridge
