services:
  h4folks-wings:
    image: ghcr.io/pelican-dev/wings:latest
    restart: unless-stopped
    networks:
      - h4folks-wings
      - projects_h4folks-panel
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - ${PWD}/data/h4folks-wings/etc:/etc/pelican
      - ${PWD}/data/h4folks-wings/logs/lib:/var/lib/pelican/"
      - ${PWD}/data/h4folks-wings/logs/log:/var/log/pelican/"
      - ${PWD}/data/h4folks-wings/tmp:/tmp/pelican
    env_file:
      - path: ${PWD}/data/h4folks-wings/.env

networks:
  h4folks-wings:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
  projects_h4folks-panel:
    external: true
