services:
  h4folks-panel:
    image: ghcr.io/pelican-dev/panel:latest
    restart: unless-stopped
    networks:
      - h4folks-panel
      - projects_caddy-net
    extra_hosts:
      - "host.docker.internal:host-gateway" # shows the panel on the internal docker network as well. usually '172.17.0.1'
    volumes:
      - ${PWD}/data/h4folks-panel:/pelican-data
      - ${PWD}/data/h4folks-panel:/var/www/html/storage/logs
    env_file:
      - path: ${PWD}/data/h4folks-panel/.env

volumes:
  pelican-data:
  pelican-logs:

networks:
  h4folks-panel:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  projects_caddy-net:
    external: true
