services:
  parsebotkyiv:
    # https://github.com/salko-ua/PARSEBOT-KYIV/commit/d28ff5e881bb21bfb608cfca3ecbc8a275a83020
    # next versions are broken because server CPU is too old
    image: salkoua/parsebotkyiv@sha256:18e09bafae0cbde30a2e1c7ffe67258642b3e6e9d3924d942b97f67b69797f03
    restart: unless-stopped
    volumes:
      - ${PWD}/data/parsebotkyiv:/app/data
    env_file:
      - path: ${PWD}/data/parsebotkyiv/.env
