services:
  pinger-bot:
    image: perchunpak/pinger-bot:latest-sqlite
    restart: unless-stopped
    volumes:
      - ${PWD}/data/pinger-bot:/app/pinger/data
    env_file:
      - path: ${PWD}/data/pinger-bot/.env
