services:
  salo-db:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    ports:
      - 5745:5432
    volumes:
      - ${PWD}/data/salo-db/data:/var/lib/postgresql/data
    env_file:
      - path: ${PWD}/data/salo-db/.env

