services:
  short-it:
    image: perchunpak/short-it
    restart: unless-stopped
    volumes:
      - ${PWD}/data/short-it:/app/data
    networks:
      - projects_caddy-net

networks:
  projects_caddy-net:
    external: true
