services:
  statusmc-frontend:
    image: perchunpak/statusmc-frontend
    restart: unless-stopped
    networks:
      - projects_caddy-net

  statusmc-backend:
    image: perchunpak/statusmc-backend
    restart: unless-stopped
    volumes:
      - ${PWD}/data/statusmc-backend:/app/data

networks:
  projects_caddy-net:
    external: true
